version: '3.3'

services:
   mongo:
    image: mongo
    restart: always
    #environment:
            #      MONGO_INITDB_ROOT_USERNAME: root
            #MONGO_INITDB_ROOT_PASSWORD: example

   node:
     depends_on:
       - mongo
     links:
       - mongo
     command: npm start 
     image: node:latest
     ports:        
       - "8081:3000"
     working_dir: /home/app
     volumes:
      - "/srv/http/sparrow:/home/app"


     
     
     
     
     

